### ISSUE TITLE
Explicit discontinuities?

### ISSUE THREAD

**Issue by adigitoleo** [anowacki/SeisModels.jl#9]
Hi!

I'm considering writing some native (seismic) ray tracing code in Julia, but I'll need to make sure that I'm sampling critical points like discontinuities. I could calculate these using this package as is (using some sort of finite difference scheme?) but I was wondering if it could instead be of interest to add explicit (hard-coded?) discontinuity estimates to the built-in models. Is it something you'd consider adding or would you rather keep such derived information outside this package?

Cheers

**Comment by adigitoleo** [comment]
Well, I should've just written the code first off :smile:. For this 1D stuff it's super easy and really quick to get something reasonable:

```julia
function discontinuities(m::SeisModel1D, field::Symbol; depth=false, fdthresh=0.1)
    surface = Int(floor(surface_radius(m)))
    # 1km radius resolution.
    radii = 0:1:surface
    velocities = evaluate.(m, v, radii)
    # Compute velocity gradient using forward differences.
    # Get discontinuities based on a gradient threshold.
    discontinuities = Int[]
    for (r, v, dv) in zip(radii, velocities, diff(velocities))
        if abs(dv) > fdthresh
            push!(discontinuities, r)
        end
    end
    return depth ? reverse(surface .- discontinuities) : discontinuities
end
```

I can open a patch for that if you'd like (I'll give it some more tests first). Not worth hard coding discontinuities I think.

**Comment by anowacki** [comment]
Thanks very much for raising the point.   This is definitely something that should be in the package and thanks for the start of an implementation.  The API makes sense at first glance.  If you are able to open a PR, then we can discuss details there.  It might make sense to use the parameterisations of some of the model types to make this easier; hard-coding a 1 km resolution to the search may not be appropriate always.

In terms of whether to include discontinuities as a field in the model structure, I tend to agree that it may be best not to since they can usually be trivially found.  However if it's useful for certain boundaries (e.g., ICB, CMB, Moho) then I would not be averse either.

Note there is currently some code to do this sort for model-writing purposes ([`core_interface_layers`](https://github.com/anowacki/SeisModels.jl/blob/0dd50aa191a50253c43debf867f5b8a2796fbfb9/src/io.jl#L198-L258))

It's tremendous that you are thinking of writing some ray tracing code.  I would be happy to accommodate that in any way I can in SeisModels.  Layer insertion/deletion/splitting/merging might be useful functionality to have for 1D models.

**Comment by adigitoleo** [comment]
After revisiting this I think it is not needed after all, since `LinearLayeredModel`s already provide this information via the duplicated radii. For other model types I would just convert to a `LinearLayeredModel` first via the provided methods. The `core_interface_layers` may prove useful as well, thanks for pointing that out.

**Comment by adigitoleo** [comment]
OK I've opened a tiny PR with what I will probably end up using just in case you think it is worthwhile including, but this is essentially a very simple search for nonunique values in the radii of a `LinearLayeredModel`.
